version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    hostname: "rabbit"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
    - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.communicator.core.config
    environment:
    - RABBITMQ_ERLANG_COOKIE=cluster_cookie
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin